services:
  database:
    image: postgres:18
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: 0.1
          memory: 100M
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - geopostgresVolume:/var/lib/postgresql
  app:
    image: food-delivery-admin:1.0.1
    ports:
      - 8080:8080
    depends_on:
      - database
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=postgres
      - POSTGRES_HOST=database
      - POSTGRES_PORT=5432
      - POSTGRES_DB=postgres
      - POSTGRES_SSLMODE=disable
volumes:
  geopostgresVolume:
    driver: local
